import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";

const currentDir = path.dirname(fileURLToPath(import.meta.url));
const repositoryRoot = path.resolve(currentDir, "..");
const versionScript = path.join(repositoryRoot, "scripts", "version.mjs");

const VERSION_SCRIPTS = {
  "version:get": "node scripts/version.mjs get",
  "version:check": "node scripts/version.mjs check",
  "version:set": "node scripts/version.mjs set",
  "version:bump": "node scripts/version.mjs bump",
};

function writeFixtureFile(root, relativePath, content) {
  const filePath = path.join(root, relativePath);
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, content, "utf8");
  return filePath;
}

function createFixture({ version = "0.2.0", eol = "\n" } = {}) {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), "fyagent-version-test-"));
  fs.mkdirSync(path.join(root, "scripts"), { recursive: true });
  fs.copyFileSync(versionScript, path.join(root, "scripts", "version.mjs"));

  writeFixtureFile(
    root,
    "package.json",
    JSON.stringify(
      {
        name: "fyagent",
        private: true,
        scripts: VERSION_SCRIPTS,
      },
      null,
      2,
    ) + eol,
  );
  writeFixtureFile(
    root,
    "src-tauri/tauri.conf.json",
    JSON.stringify(
      {
        productName: "FyAgent",
        identifier: "com.fyagent.desktop",
      },
      null,
      2,
    ) + eol,
  );

  writeFixtureFile(
    root,
    "src-tauri/Cargo.toml",
    [
      "[workspace]",
      'members = ["."]',
      'resolver = "2"',
      "",
      "[workspace.package]",
      'version = "' + version + '"',
      "",
      "[package]",
      'name = "fyagent"',
      "version.workspace = true",
      'edition = "2021"',
      "",
    ].join(eol),
  );

  writeFixtureFile(
    root,
    "src-tauri/Cargo.lock",
    [
      "# This file is automatically @generated by Cargo.",
      "version = 4",
      "",
      "[[package]]",
      'name = "dependency-a"',
      'version = "0.2.0"',
      "",
      "[[package]]",
      'name = "fyagent"',
      'version = "' + version + '"',
      "",
      "[[package]]",
      'name = "dependency-b"',
      'version = "0.2.0"',
      "",
    ].join(eol),
  );

  return root;
}

function removeFixture(root) {
  fs.rmSync(root, { recursive: true, force: true });
}

function run(root, ...args) {
  return spawnSync(process.execPath, ["scripts/version.mjs", ...args], {
    cwd: root,
    encoding: "utf8",
  });
}

function runWithEnvironment(root, environment, ...args) {
  return spawnSync(process.execPath, ["scripts/version.mjs", ...args], {
    cwd: root,
    encoding: "utf8",
    env: { ...process.env, ...environment },
  });
}

function readFixture(root, relativePath) {
  return fs.readFileSync(path.join(root, relativePath), "utf8");
}

function writeFixture(root, relativePath, content) {
  fs.writeFileSync(path.join(root, relativePath), content, "utf8");
}

function readJsonFixture(root, relativePath) {
  return JSON.parse(readFixture(root, relativePath));
}

function writeJsonFixture(root, relativePath, value) {
  writeFixture(root, relativePath, JSON.stringify(value, null, 2) + "\n");
}

function versionTemporaryFiles(root) {
  return fs
    .readdirSync(path.join(root, "src-tauri"))
    .filter((name) => name.includes(".fyagent-version-"));
}

test("set applies only the canonical Cargo value and local lock entries", (t) => {
  const root = createFixture();
  t.after(() => removeFixture(root));

  const packageBefore = readFixture(root, "package.json");
  const tauriBefore = readFixture(root, "src-tauri/tauri.conf.json");
  const result = run(root, "set", "0.2.1", "--apply");

  assert.equal(result.status, 0, result.stderr);
  assert.match(
    readFixture(root, "src-tauri/Cargo.toml"),
    /\[workspace\.package\][\s\S]*version = "0\.2\.1"/,
  );

  const lock = readFixture(root, "src-tauri/Cargo.lock");
  assert.match(lock, /name = "fyagent"\nversion = "0\.2\.1"/);
  assert.equal(
    (lock.match(/name = "dependency-[ab]"\nversion = "0\.2\.0"/g) ?? []).length,
    2,
  );
  assert.equal(readFixture(root, "package.json"), packageBefore);
  assert.equal(readFixture(root, "src-tauri/tauri.conf.json"), tauriBefore);
  assert.deepEqual(versionTemporaryFiles(root), []);
});

test("check enforces exact release tag equality", (t) => {
  const root = createFixture();
  t.after(() => removeFixture(root));

  assert.equal(run(root, "check", "--", "--tag", "v0.2.0").status, 0);
  const mismatch = run(root, "check", "--", "--tag", "v0.2.1");
  assert.equal(mismatch.status, 1);
  assert.match(mismatch.stderr, /release tag must be v0\.2\.0/);
});

test("get prints only the canonical application version", (t) => {
  const root = createFixture();
  t.after(() => removeFixture(root));

  const result = run(root, "get");
  assert.equal(result.status, 0, result.stderr);
  assert.equal(result.stdout, "0.2.0\n");
  assert.equal(result.stderr, "");
});

test("set rejects prerelease and v-prefixed values", (t) => {
  const root = createFixture();
  t.after(() => removeFixture(root));

  for (const invalid of ["v0.2.1", "0.2.1-beta.1", "0.2.1+build.2"]) {
    const result = run(root, "set", invalid);
    assert.equal(result.status, 1, invalid + ": " + result.stderr);
  }
  assert.match(run(root, "set", "v0.2.1").stderr, /stable SemVer X\.Y\.Z/);
});

test("set previews by default and --dry-run is the same non-writing mode", (t) => {
  const root = createFixture();
  t.after(() => removeFixture(root));
  const cargoBefore = readFixture(root, "src-tauri/Cargo.toml");
  const lockBefore = readFixture(root, "src-tauri/Cargo.lock");

  const preview = run(root, "set", "0.2.1");
  const dryRun = run(root, "set", "0.2.1", "--dry-run");
  assert.equal(preview.status, 0, preview.stderr);
  assert.equal(dryRun.status, 0, dryRun.stderr);
  assert.equal(preview.stdout, dryRun.stdout);
  assert.match(preview.stdout, /would update src-tauri\/Cargo\.toml/);
  assert.match(preview.stdout, /would update src-tauri\/Cargo\.lock/);
  assert.equal(readFixture(root, "src-tauri/Cargo.toml"), cargoBefore);
  assert.equal(readFixture(root, "src-tauri/Cargo.lock"), lockBefore);
});

test("write authorization flags reject conflicts and read commands reject apply", (t) => {
  const root = createFixture();
  t.after(() => removeFixture(root));

  const conflict = run(root, "set", "0.2.1", "--apply", "--dry-run");
  assert.equal(conflict.status, 1);
  assert.match(conflict.stderr, /mutually exclusive/);

  for (const command of ["get", "check"]) {
    const result = run(root, command, "--apply");
    assert.equal(result.status, 1, command + ": " + result.stderr);
  }
});

test("apply is a no-op when all canonical values already match", (t) => {
  const root = createFixture();
  t.after(() => removeFixture(root));
  const cargoPath = path.join(root, "src-tauri", "Cargo.toml");
  const lockPath = path.join(root, "src-tauri", "Cargo.lock");
  const cargoBefore = fs.statSync(cargoPath);
  const lockBefore = fs.statSync(lockPath);

  const result = run(root, "set", "0.2.0", "--apply");

  assert.equal(result.status, 0, result.stderr);
  assert.match(result.stdout, /version already matched; no files changed/);
  assert.equal(fs.statSync(cargoPath).mtimeMs, cargoBefore.mtimeMs);
  assert.equal(fs.statSync(lockPath).mtimeMs, lockBefore.mtimeMs);
});

test("bump implements stable SemVer arithmetic", (t) => {
  const cases = [
    ["patch", "0.2.1"],
    ["minor", "0.3.0"],
    ["major", "1.0.0"],
  ];

  for (const [kind, expected] of cases) {
    const root = createFixture();
    t.after(() => removeFixture(root));
    const result = run(root, "bump", kind, "--apply");
    assert.equal(result.status, 0, kind + ": " + result.stderr);
    const getResult = run(root, "get");
    assert.equal(getResult.status, 0, getResult.stderr);
    assert.equal(getResult.stdout.trim(), expected);
  }
});

test("set and bump preserve stable SemVer components beyond former packager limits", (t) => {
  const root = createFixture({ version: "9007199254740993.256.65536" });
  t.after(() => removeFixture(root));

  const checkResult = run(root, "check");
  assert.equal(checkResult.status, 0, checkResult.stderr);

  const bumpResult = run(root, "bump", "patch", "--apply");
  assert.equal(bumpResult.status, 0, bumpResult.stderr);
  assert.equal(run(root, "get").stdout.trim(), "9007199254740993.256.65537");
});

test("set rejects components outside Cargo's SemVer range", (t) => {
  const root = createFixture();
  t.after(() => removeFixture(root));

  const result = run(root, "set", "18446744073709551616.0.0", "--apply");
  assert.equal(result.status, 1);
  assert.match(result.stderr, /Cargo's unsigned 64-bit SemVer component range/);
  assert.equal(run(root, "get").stdout.trim(), "0.2.0");
});

test("check rejects duplicate metadata fields and a missing command", (t) => {
  const root = createFixture();
  t.after(() => removeFixture(root));

  const packageJson = readJsonFixture(root, "package.json");
  packageJson.version = "0.2.0";
  delete packageJson.scripts["version:check"];
  writeJsonFixture(root, "package.json", packageJson);

  const tauriPath = "src-tauri/tauri.conf.json";
  const tauriConfig = readJsonFixture(root, tauriPath);
  tauriConfig.version = "0.2.0";
  writeJsonFixture(root, tauriPath, tauriConfig);

  const result = run(root, "check");
  assert.equal(result.status, 1);
  assert.match(result.stderr, /package\.json must not declare/);
  assert.match(result.stderr, /scripts\.version:check/);
  assert.match(result.stderr, /tauri\.conf\.json must omit version/);
});

test("check requires workspace shape and package inheritance", (t) => {
  const root = createFixture();
  t.after(() => removeFixture(root));
  const cargoPath = "src-tauri/Cargo.toml";

  writeFixture(
    root,
    cargoPath,
    readFixture(root, cargoPath)
      .replace('members = ["."]', 'members = [".", "unexpected"]')
      .replace('resolver = "2"', 'resolver = "1"')
      .replace("version.workspace = true", 'version = "0.2.0"'),
  );

  const result = run(root, "check");
  assert.equal(result.status, 1);
  assert.match(result.stderr, /members must be/);
  assert.match(result.stderr, /resolver must be "2"/);
  assert.match(result.stderr, /must use exactly one version\.workspace/);
});

test("check rejects duplicate Cargo sections and local lock version fields", (t) => {
  const duplicateSection = createFixture();
  t.after(() => removeFixture(duplicateSection));
  const cargoPath = "src-tauri/Cargo.toml";
  writeFixture(
    duplicateSection,
    cargoPath,
    readFixture(duplicateSection, cargoPath) +
      '\n[workspace.package]\nversion = "0.2.0"\n',
  );

  let result = run(duplicateSection, "check");
  assert.equal(result.status, 1);
  assert.match(
    result.stderr,
    /must declare \[workspace\.package\] exactly once; found 2/,
  );

  const duplicateLockVersion = createFixture();
  t.after(() => removeFixture(duplicateLockVersion));
  const lockPath = "src-tauri/Cargo.lock";
  writeFixture(
    duplicateLockVersion,
    lockPath,
    readFixture(duplicateLockVersion, lockPath).replace(
      'name = "fyagent"\nversion = "0.2.0"',
      'name = "fyagent"\nversion = "0.2.0"\nversion = "0.2.0"',
    ),
  );

  result = run(duplicateLockVersion, "check");
  assert.equal(result.status, 1);
  assert.match(result.stderr, /must contain exactly one version/);
});

test("check rejects missing or non-local workspace lock package entries", (t) => {
  const root = createFixture();
  t.after(() => removeFixture(root));
  const lockPath = "src-tauri/Cargo.lock";
  const original = readFixture(root, lockPath);

  writeFixture(
    root,
    lockPath,
    original.replace(
      'name = "fyagent"\nversion = "0.2.0"',
      'name = "fyagent"\nversion = "0.2.0"\nsource = "registry+https://example.invalid"',
    ),
  );
  let result = run(root, "check");
  assert.equal(result.status, 1);
  assert.match(
    result.stderr,
    /must be a local workspace package without source/,
  );

  writeFixture(
    root,
    lockPath,
    original.replace(
      '\n[[package]]\nname = "fyagent"\nversion = "0.2.0"\n',
      "\n",
    ),
  );
  result = run(root, "check");
  assert.equal(result.status, 1);
  assert.match(result.stderr, /missing local package fyagent/);
});

test("set repairs version drift in local lock entries without touching dependencies", (t) => {
  const root = createFixture();
  t.after(() => removeFixture(root));
  const lockPath = "src-tauri/Cargo.lock";
  const drifted = readFixture(root, lockPath).replace(
    'name = "fyagent"\nversion = "0.2.0"',
    'name = "fyagent"\nversion = "0.1.9"',
  );
  writeFixture(root, lockPath, drifted);

  const result = run(root, "set", "0.2.1", "--apply");
  assert.equal(result.status, 0, result.stderr);
  const lock = readFixture(root, lockPath);
  assert.match(lock, /name = "fyagent"\nversion = "0\.2\.1"/);
  assert.match(lock, /name = "dependency-a"\nversion = "0\.2\.0"/);
  assert.match(lock, /name = "dependency-b"\nversion = "0\.2\.0"/);
});

test("set refuses an invalid structural contract before writing", (t) => {
  const root = createFixture();
  t.after(() => removeFixture(root));
  const packagePath = "package.json";
  const packageJson = readJsonFixture(root, packagePath);
  packageJson.version = "0.2.0";
  writeJsonFixture(root, packagePath, packageJson);

  const cargoBefore = readFixture(root, "src-tauri/Cargo.toml");
  const lockBefore = readFixture(root, "src-tauri/Cargo.lock");
  const result = run(root, "set", "0.2.1", "--apply");
  assert.equal(result.status, 1);
  assert.match(result.stderr, /cannot update an invalid version contract/);
  assert.equal(readFixture(root, "src-tauri/Cargo.toml"), cargoBefore);
  assert.equal(readFixture(root, "src-tauri/Cargo.lock"), lockBefore);
});

test("set never truncates the target or leaves a partial temporary file", (t) => {
  const root = createFixture();
  t.after(() => removeFixture(root));
  const hookPath = path.join(root, "fail-temporary-write.cjs");
  writeFixture(
    root,
    "fail-temporary-write.cjs",
    [
      'const fs = require("node:fs");',
      "const originalOpenSync = fs.openSync;",
      "const originalWriteFileSync = fs.writeFileSync;",
      "const originalWriteSync = fs.writeSync;",
      "const temporaryDescriptors = new Set();",
      "let injected = false;",
      "fs.openSync = function patchedOpenSync(filePath, ...args) {",
      "  const descriptor = originalOpenSync.call(this, filePath, ...args);",
      '  if (String(filePath).includes(".Cargo.toml.fyagent-version-")) {',
      "    temporaryDescriptors.add(descriptor);",
      "  }",
      "  return descriptor;",
      "};",
      "fs.writeFileSync = function patchedWriteFileSync(file, data, ...args) {",
      '  if (!injected && process.env.FYAGENT_VERSION_TEST_FAIL_TEMP_WRITE === "1" &&',
      "      temporaryDescriptors.has(file)) {",
      "    injected = true;",
      '    originalWriteSync.call(fs, file, Buffer.from("partial"));',
      '    const error = new Error("injected temporary write failure");',
      '    error.code = "EIO";',
      "    throw error;",
      "  }",
      "  return originalWriteFileSync.call(this, file, data, ...args);",
      "};",
      "",
    ].join("\n"),
  );

  const cargoBefore = readFixture(root, "src-tauri/Cargo.toml");
  const lockBefore = readFixture(root, "src-tauri/Cargo.lock");
  const nodeOptions = [process.env.NODE_OPTIONS ?? "", "--require=" + hookPath]
    .filter(Boolean)
    .join(" ");
  const result = runWithEnvironment(
    root,
    {
      FYAGENT_VERSION_TEST_FAIL_TEMP_WRITE: "1",
      NODE_OPTIONS: nodeOptions,
    },
    "set",
    "0.2.1",
    "--apply",
  );

  assert.equal(result.status, 1);
  assert.match(result.stderr, /injected temporary write failure/);
  assert.equal(readFixture(root, "src-tauri/Cargo.toml"), cargoBefore);
  assert.equal(readFixture(root, "src-tauri/Cargo.lock"), lockBefore);
  assert.deepEqual(versionTemporaryFiles(root), []);
});

test("set restores the canonical value when a later lock replacement fails", (t) => {
  const root = createFixture();
  t.after(() => removeFixture(root));
  const hookPath = path.join(root, "fail-lock-replacement.cjs");
  writeFixture(
    root,
    "fail-lock-replacement.cjs",
    [
      'const fs = require("node:fs");',
      'const path = require("node:path");',
      "const originalRenameSync = fs.renameSync;",
      "let injected = false;",
      "fs.renameSync = function patchedRenameSync(source, destination) {",
      '  if (!injected && process.env.FYAGENT_VERSION_TEST_FAIL_LOCK_RENAME === "1" &&',
      '      path.basename(String(destination)) === "Cargo.lock" &&',
      "      fs.readFileSync(source, 'utf8').includes('version = \"0.2.1\"')) {",
      "    injected = true;",
      '    const error = new Error("injected Cargo.lock replacement failure");',
      '    error.code = "EIO";',
      "    throw error;",
      "  }",
      "  return originalRenameSync.call(this, source, destination);",
      "};",
      "",
    ].join("\n"),
  );

  const cargoBefore = readFixture(root, "src-tauri/Cargo.toml");
  const lockBefore = readFixture(root, "src-tauri/Cargo.lock");
  const nodeOptions = [process.env.NODE_OPTIONS ?? "", "--require=" + hookPath]
    .filter(Boolean)
    .join(" ");
  const result = runWithEnvironment(
    root,
    {
      FYAGENT_VERSION_TEST_FAIL_LOCK_RENAME: "1",
      NODE_OPTIONS: nodeOptions,
    },
    "set",
    "0.2.1",
    "--apply",
  );

  assert.equal(result.status, 1);
  assert.match(result.stderr, /rollback succeeded/);
  assert.equal(readFixture(root, "src-tauri/Cargo.toml"), cargoBefore);
  assert.equal(readFixture(root, "src-tauri/Cargo.lock"), lockBefore);
  assert.deepEqual(versionTemporaryFiles(root), []);
});

test("set rolls both files back when post-write contract verification fails", (t) => {
  const root = createFixture();
  t.after(() => removeFixture(root));
  const hookPath = path.join(root, "fail-post-write-check.cjs");
  writeFixture(
    root,
    "fail-post-write-check.cjs",
    [
      'const fs = require("node:fs");',
      'const path = require("node:path");',
      "const originalRenameSync = fs.renameSync;",
      "const originalWriteFileSync = fs.writeFileSync;",
      "let injected = false;",
      "fs.renameSync = function patchedRenameSync(source, destination) {",
      '  if (!injected && process.env.FYAGENT_VERSION_TEST_FAIL_POST_CHECK === "1" &&',
      '      path.basename(String(destination)) === "Cargo.lock" &&',
      "      fs.readFileSync(source, 'utf8').includes('version = \"0.2.1\"')) {",
      "    const result = originalRenameSync.call(this, source, destination);",
      "    injected = true;",
      '    const packagePath = path.join(path.dirname(String(destination)), "..", "package.json");',
      '    const packageJson = JSON.parse(fs.readFileSync(packagePath, "utf8"));',
      '    packageJson.version = "0.2.1";',
      '    originalWriteFileSync.call(fs, packagePath, JSON.stringify(packageJson), "utf8");',
      "    return result;",
      "  }",
      "  return originalRenameSync.call(this, source, destination);",
      "};",
      "",
    ].join("\n"),
  );

  const cargoBefore = readFixture(root, "src-tauri/Cargo.toml");
  const lockBefore = readFixture(root, "src-tauri/Cargo.lock");
  const nodeOptions = [process.env.NODE_OPTIONS ?? "", "--require=" + hookPath]
    .filter(Boolean)
    .join(" ");
  const result = runWithEnvironment(
    root,
    {
      FYAGENT_VERSION_TEST_FAIL_POST_CHECK: "1",
      NODE_OPTIONS: nodeOptions,
    },
    "set",
    "0.2.1",
    "--apply",
  );

  assert.equal(result.status, 1);
  assert.match(result.stderr, /failed contract verification/);
  assert.match(result.stderr, /rollback succeeded/);
  assert.equal(readFixture(root, "src-tauri/Cargo.toml"), cargoBefore);
  assert.equal(readFixture(root, "src-tauri/Cargo.lock"), lockBefore);
  assert.deepEqual(versionTemporaryFiles(root), []);
});

test("apply preserves CRLF Cargo manifests and lockfiles", (t) => {
  const root = createFixture({ eol: "\r\n" });
  t.after(() => removeFixture(root));

  const checkResult = run(root, "check");
  assert.equal(checkResult.status, 0, checkResult.stderr);
  const setResult = run(root, "set", "0.2.1", "--apply");
  assert.equal(setResult.status, 0, setResult.stderr);
  assert.equal(run(root, "check").status, 0);
  assert.doesNotMatch(readFixture(root, "src-tauri/Cargo.toml"), /(?<!\r)\n/);
  assert.doesNotMatch(readFixture(root, "src-tauri/Cargo.lock"), /(?<!\r)\n/);
});
